anki/urls.py
"""
anki/urls.py
"""
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page
from anki import settings
from cards import views
from django.conf.urls.static import static
from django.conf import settings


# Настраиваем заголовки админ-панели
admin.site.site_header = "Управление моим сайтом" # Текст в шапке
admin.site.site_title = "Административный сайт" # Текст в титле
admin.site.index_title = "Добро пожаловать в панель управления" # Текст на главной странице




urlpatterns = [
    # Админка
    path('admin/', admin.site.urls),
    # Маршруты для меню
    path('', cache_page(60*15)(views.IndexView.as_view()), name='index'),
    path('about/', cache_page(60*15)(views.AboutView.as_view()), name='about'), 
    # Маршруты подключенные из приложения cards
    path('cards/', include('cards.urls')),
    path('users/', include('users.urls', namespace='users')),
    # Маршруты для авторизации через соцсети
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                      # другие URL-паттерны
                  ] + urlpatterns
    
    # Добавляем обработку медиафайлов
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Определяем кастомный обработчик 404 ошибки
handler404 = views.PageNotFoundView.as_view()

users/urls.py
from django.urls import path
from . import views

# Иморт служебных функций для работы с пользователями. django.contrib.auth - это встроенное приложение Django, которое предоставляет функционал для работы с пользователями.
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'users'  # Пространство имен для приложения

urlpatterns = [
    # Вход / Выход / Регистрация
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),
    path('signup/', views.RegisterUser.as_view(), name='signup'),
    # Сообщение об успешной регистрации
    path('register_done/', views.RegisterDoneView.as_view(), name='register_done'),
    # Профиль / Изменение пароля / Мои карточки / Избранное
    path("profile/", views.ProfileUser.as_view(), name='profile'),
    path("password_change/", views.UserPasswordChange.as_view(), name='password_change'),
    path("passwor_change_done/", views.UserPasswordChangeDone.as_view(), name='password_change_done'),
    path("profile_cards/", views.UserCardsView.as_view(), name='profile_cards'),
    path("profile_favorites/", views.UserFavoritesView.as_view(), name='profile_favorites'),
    # Профиль / Восстановление пароля
    #########

    # Маршрут для сброса пароля
    path("password-reset/", auth_views.PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ), name="password_reset",
    ),
    
    # Маршрут для подтверждения сброса пароля
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ), name="password_reset_done",
    ),
    
    # Маршрут для ввода нового пароля
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ), name="password_reset_confirm",
    ),
    
    # Маршрут для завершения сброса пароля
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),name="password_reset_complete",
    ),

    # Маршруты автризации через соцсети
    path('link-social-account/', views.SocialAuthView.as_view(), name='link_social_account'),
    path('save-oauth-data/<str:backend>/', views.SocialAuthView.as_view(), name='save_oauth_data'),

]

templates/include/markdown_to_html_tag.html
<mark>
    {{ markdown_text|safe }}
</mark>

templates/include/nav_menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <!-- Логотип и кнопка для мобильных версий -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Ссылки навигации и аутентификация -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto"> <!-- me-auto класс выравнивает элементы меню по левому краю -->
        {% for item in menu %}
        <li class="nav-item">
          <a class="nav-link {% if forloop.first %}active{% endif %}" aria-current="page" href="{% url item.url_name %}">{{ item.title }}</a>
        </li>
        {% endfor %}
      </ul>
      <ul class="navbar-nav"> <!-- Элементы правой части без выравнивания по левому краю -->
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>