anki/urls.py
"""
anki/urls.py
"""
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page
from anki import settings
from cards import views
from django.conf.urls.static import static
from django.conf import settings


# Настраиваем заголовки админ-панели
admin.site.site_header = "Управление моим сайтом" # Текст в шапке
admin.site.site_title = "Административный сайт" # Текст в титле
admin.site.index_title = "Добро пожаловать в панель управления" # Текст на главной странице




urlpatterns = [
    # Админка
    path('admin/', admin.site.urls),
    # Маршруты для меню
    path('', cache_page(60*15)(views.IndexView.as_view()), name='index'),
    path('about/', cache_page(60*15)(views.AboutView.as_view()), name='about'), 
    # Маршруты подключенные из приложения cards
    path('cards/', include('cards.urls')),
    path('users/', include('users.urls', namespace='users')),
    # Маршруты для авторизации через соцсети
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                      # другие URL-паттерны
                  ] + urlpatterns
    
    # Добавляем обработку медиафайлов
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Определяем кастомный обработчик 404 ошибки
handler404 = views.PageNotFoundView.as_view()

users/urls.py
from django.urls import path
from . import views

# Иморт служебных функций для работы с пользователями. django.contrib.auth - это встроенное приложение Django, которое предоставляет функционал для работы с пользователями.
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'users'  # Пространство имен для приложения

urlpatterns = [
    # Вход / Выход / Регистрация
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),
    path('signup/', views.RegisterUser.as_view(), name='signup'),
    # Сообщение об успешной регистрации
    path('register_done/', views.RegisterDoneView.as_view(), name='register_done'),
    # Профиль / Изменение пароля / Мои карточки / Избранное
    path("profile/", views.ProfileUser.as_view(), name='profile'),
    path("password_change/", views.UserPasswordChange.as_view(), name='password_change'),
    path("passwor_change_done/", views.UserPasswordChangeDone.as_view(), name='password_change_done'),
    path("profile_cards/", views.UserCardsView.as_view(), name='profile_cards'),
    path("profile_favorites/", views.UserFavoritesView.as_view(), name='profile_favorites'),
    # Профиль / Восстановление пароля
    #########

    # Маршрут для сброса пароля
    path("password-reset/", auth_views.PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ), name="password_reset",
    ),
    
    # Маршрут для подтверждения сброса пароля
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ), name="password_reset_done",
    ),
    
    # Маршрут для ввода нового пароля
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ), name="password_reset_confirm",
    ),
    
    # Маршрут для завершения сброса пароля
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),name="password_reset_complete",
    ),

    # Маршруты автризации через соцсети
    path('link-social-account/', views.SocialAuthView.as_view(), name='link_social_account'),
    path('save-oauth-data/<str:backend>/', views.SocialAuthView.as_view(), name='save_oauth_data'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    photo = models.ImageField(upload_to='users/images/%Y/%m/%d/', blank=True, null=True, verbose_name='Фотография')
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')
    github_id = models.CharField(max_length=255, blank=True, null=True)
    vk_id = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.core.exceptions import ValidationError
import datetime

class RegisterUserForm(UserCreationForm):
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name')
        labels = {
            'email': 'E-Mail',
            'first_name': 'Имя'
        }

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise ValidationError('Данный адрес электронной почты уже зарегистрирован в системе')
        return email

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя | Email', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class ProfileUserForm(forms.ModelForm):
    this_year = datetime.date.today().year
    date_birth = forms.DateField(
        label='Дата рождения',
        widget=forms.SelectDateWidget(years=range(this_year - 100, this_year - 5)),
        required=False
    )
    photo = forms.ImageField(
        label='Фотография',
        required=False
    )
    
    
    username = forms.CharField(
        disabled=True,  # Поле не редактируемое
        label='Логин',
        widget=forms.TextInput(attrs={'class': 'form-control'})  # Использование Bootstrap класса
    )
    email = forms.CharField(
        disabled=True,  # Поле не редактируемое
        label='E-mail',
        widget=forms.TextInput(attrs={'class': 'form-control'})  # Использование Bootstrap класса
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'date_birth', 'photo']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'date_birth': 'Дата рождения',
            'photo': 'Фотография'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'})
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Старый пароль'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Новый пароль'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтверждение нового пароля'}))
    

users/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import logout
from django.views import View
from .forms import CustomAuthenticationForm, RegisterUserForm
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse_lazy
from cards.views import MenuMixin
from django.views.generic import TemplateView, CreateView, ListView
from django.contrib.auth import get_user_model
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ProfileUserForm, UserPasswordChangeForm
from cards.models import Card
from social_django.utils import psa


class LoginUser(MenuMixin, LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}
    redirect_field_name = 'next'

    def get_success_url(self):
        if self.request.POST.get('next', '').strip():
            return self.request.POST.get('next')
        return reverse_lazy('catalog')

class LogoutUser(LogoutView):
    next_page = reverse_lazy('users:login')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:register_done')


class RegisterDoneView(MenuMixin, TemplateView):
    template_name = 'users/register_done.html'
    extra_context = {'title': 'Регистрация завершена'}


class ProfileUser(MenuMixin, LoginRequiredMixin, UpdateView):
    model = get_user_model()  # Используем модель текущего пользователя
    form_class = ProfileUserForm  # Связываем с формой профиля пользователя
    template_name = 'users/profile.html'  # Указываем путь к шаблону
    extra_context = {'title': 'Профиль пользователя','active_tab': 'profile'}  # Дополнительный контекст для передачи в шаблон

    def get_success_url(self):
        # URL, на который переадресуется пользователь после успешного обновления
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        # Возвращает объект модели, который должен быть отредактирован
        # Проверят входит ли пользователь в группу "Модераторы",если да то user.moderator = True
        # Это самая убогая версия, но она работает))
        # Более качественный вариант - контекстный процессор! Он поместит эту проверку во все шаблоны
        user = self.request.user
        if user.groups.filter(name='Модераторы').exists():
            user.moderator = True
        return self.request.user


class UserPasswordChange(MenuMixin, PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'users/password_change_form.html'
    extra_context = {'title': 'Изменение пароля',
                     'active_tab': 'password_change'}
    success_url = reverse_lazy('users:password_change_done')


class UserPasswordChangeDone(MenuMixin, TemplateView):
    template_name = 'users/password_change_done.html'
    extra_context = {'title': 'Пароль изменен успешно'}


class UserCardsView(MenuMixin, ListView):
    model = Card
    template_name = 'users/profile_cards.html'
    context_object_name = 'cards'
    extra_context = {'title': 'Мои карточки',
                     'active_tab': 'profile_cards'}

    def get_queryset(self):
        return Card.objects.filter(author=self.request.user).order_by('-upload_date')


class UserFavoritesView(MenuMixin, ListView):
    model = Card
    template_name = 'users/profile_cards.html'
    context_object_name = 'cards'
    extra_context = {'title': 'Избранные карточки',
                     'active_tab': 'profile_favorites'}
    
    def get_queryset(self):
        return self.request.user.favorite_cards.all().order_by('-upload_date')

class SocialAuthView(View):

    @psa('social:complete')
    def save_oauth_data(self, request, backend):
        user = request.user
        if backend.name == 'github':
            user.github_id = backend.get_user_id(request)
        elif backend.name == 'vk':
            user.vk_id = backend.get_user_id(request)
        user.save()
        return redirect('users:profile')

    def post(self, request, *args, **kwargs):
        if 'provider' in request.POST:
            provider = request.POST['provider']
            if provider == 'github':
                return redirect('social:begin', backend='github')
            elif provider == 'vk':
                return redirect('social:begin', backend='vk')
        return redirect('users:profile')

users/templates/users/base_profile.html
{% extends "base.html" %} {% block content %}

<div class="row">
  <div class="col-md-3">
    {% comment %} Вставка меню {% endcomment %} 
    {% include "include/profile_nav.html" %}
    
  </div>
  <div class="col-md-9">
    {% block content_profile %}
    {% endblock %}
  </div>
</div>

{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    {% comment %} Полоса BS5. На больших экранах 6 кол. на маленьких 12 {% endcomment %}
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <h2>Вход в систему</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                <button type="submit" class="btn btn-dark">Войти</button>
            </form>
            <h3>Или зайдите через:</h3>
            <a href="{% url 'social:begin' 'vk' %}" class="btn btn-dark">ВКонтакте</a>
            <a href="{% url 'social:begin' 'github' %}" class="btn btn-dark">GitHub</a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_change_done.html
{% extends "base.html" %}
{% block content %}
<p>Ваш пароль был успешно изменен.</p>
<a href="{% url 'index' %}" class="btn btn-dark">Вернуться на главную</a>
{% endblock %}

users/templates/users/password_change_form.html
{% extends "users/base_profile.html" %}
{% load static %}
{% block content_profile %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-dark">Сменить пароль</button>
</form>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">{% trans "Ваш пароль был успешно изменен." %}</h4>
  <p>{% trans "Теперь вы можете войти с новым паролем." %}</p>
  <a href="{% url 'users:login' %}" class="btn btn-dark">Войти</a>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Ввод нового пароля" %}</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="mb-3">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
            {% endfor %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-dark">{% trans "Изменить пароль" %}</button>
</form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Сброс пароля" %}</h2>
<p>{% trans "На вашу электронную почту были отправлены инструкции по восстановлению пароля." %}</p>
{% endblock %}

users/templates/users/password_reset_email.html
{% comment %} Это письмо для сброса пароля  {% endcomment %}
{% load i18n %}
{% autoescape off %}
Здравствуйте!

Мы получили запрос на сброс пароля для вашей учетной записи. Если вы не делали этот запрос, пожалуйста, проигнорируйте это письмо.

Чтобы сбросить ваш пароль, нажмите на ссылку ниже (или скопируйте и вставьте URL в ваш браузер):

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}


С уважением,
Команда {{ site_name }}
{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Восстановление пароля" %}</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="mb-3">
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
        <div class="form-text">{{ field.help_text }}</div>
        {% endif %}
        {% for error in field.errors %}
        <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-dark">{% trans "Сбросить пароль" %}</button>
</form>
{% endblock %}

users/templates/users/profile.html
{% extends "users/base_profile.html" %}
{% load static %}
{% comment %} Добавим стили - чтобы фотография была кругом и не более 400 пикселей {% endcomment %}
{% block head %}
<style>
  .profile-img {
    border-radius: 45%;
    max-width: 60%;
    border: 2px solid #000;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
  }
</style>
{% endblock %}

{% block content_profile %}
{% comment %} ТУТ Форма профиля {% endcomment %} 
<h2>Изменение профиля
{% comment %} Если пользователь состоит в группе "Модераторы" {% endcomment %}
{% if user.moderator %}
<i class="bi bi-vector-pen"></i>
{% endif %}
</h2>
<form method="post" action="{% url 'users:link_social_account' %}">
  {% csrf_token %}
  <button type="submit" name="provider" value="github" class="btn btn-dark">Привязать GitHub</button>
  <button type="submit" name="provider" value="vk" class="btn btn-dark">Привязать VK</button>
</form>

{% comment %} Выводим фото пользователя в Image fluid BS5 {% endcomment %}
{% if user.photo %}
<div class="text-center mt-5 mb-3">
<img class="profile-img" src="{{ user.photo.url }}" class="img-fluid" alt="Тут фото {{ user.username }}">
{% endif %}
</div>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-dark">Сохранить</button>
</form>
{% endblock %}
      

                    

users/templates/users/profile_cards.html
{% extends "users/base_profile.html" %}
{% load static %}
{% block content_profile %}
{% comment %} ТУТ Карточки {% endcomment %} 
{% for card in cards %} 
{%include "cards/include/card_preview.html" %}
{% endfor %}
{% endblock %}
      

users/templates/users/register.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    {% comment %} Полоса BS5. На больших экранах 6 кол. на маленьких 12 {% endcomment %}
    <div class="row">
        <div class="col-12 col-md-8 offset-md-3">
            <h2>Регистрация</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                <button type="submit" class="btn btn-dark">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
<p>Вы успешно зарегистрировались. <a href="{% url 'users:login' %}">Авторизуйтесь</a>.</p>
{% endblock %}